const bankData = [
  {
    "customer_id": 1,
    "credit_score": 619,
    "geography": "France",
    "gender": "Male",
    "age": 42,
    "tenure": 2,
    "balance": 0.0,
    "num_of_products": 1,
    "has_credit_card": 1,
    "is_active_member": 1,
    "estimated_salary": 101348.88,
    "churned": 0
  },
  {
    "customer_id": 2,
    "credit_score": 608,
    "geography": "Spain",
    "gender": "Female",
    "age": 41,
    "tenure": 1,
    "balance": 83807.86,
    "num_of_products": 1,
    "has_credit_card": 0,
    "is_active_member": 1,
    "estimated_salary": 112542.58,
    "churned": 0
  },
  {
    "customer_id": 3,
    "credit_score": 502,
    "geography": "France",
    "gender": "Male",
    "age": 42,
    "tenure": 8,
    "balance": 159660.8,
    "num_of_products": 3,
    "has_credit_card": 1,
    "is_active_member": 0,
    "estimated_salary": 113931.57,
    "churned": 1
  },
  {
    "customer_id": 4,
    "credit_score": 699,
    "geography": "France",
    "gender": "Female",
    "age": 39,
    "tenure": 1,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 0,
    "is_active_member": 0,
    "estimated_salary": 93826.63,
    "churned": 0
  },
  {
    "customer_id": 5,
    "credit_score": 850,
    "geography": "Spain",
    "gender": "Male",
    "age": 43,
    "tenure": 2,
    "balance": 125510.82,
    "num_of_products": 1,
    "has_credit_card": 1,
    "is_active_member": 1,
    "estimated_salary": 79084.1,
    "churned": 0
  },
  {
    "customer_id": 6,
    "credit_score": 645,
    "geography": "Spain",
    "gender": "Female",
    "age": 44,
    "tenure": 8,
    "balance": 113755.78,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 0,
    "estimated_salary": 149756.71,
    "churned": 1
  },
  {
    "customer_id": 7,
    "credit_score": 822,
    "geography": "Germany",
    "gender": "Male",
    "age": 53,
    "tenure": 2,
    "balance": 0.0,
    "num_of_products": 1,
    "has_credit_card": 1,
    "is_active_member": 1,
    "estimated_salary": 10062.8,
    "churned": 0
  },
  {
    "customer_id": 8,
    "credit_score": 376,
    "geography": "Germany",
    "gender": "Female",
    "age": 50,
    "tenure": 7,
    "balance": 142051.07,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 1,
    "estimated_salary": 119346.88,
    "churned": 1
  },
  {
    "customer_id": 9,
    "credit_score": 501,
    "geography": "France",
    "gender": "Male",
    "age": 45,
    "tenure": 3,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 0,
    "is_active_member": 0,
    "estimated_salary": 74940.5,
    "churned": 0
  },
  {
    "customer_id": 10,
    "credit_score": 684,
    "geography": "France",
    "gender": "Female",
    "age": 52,
    "tenure": 2,
    "balance": 134603.89,
    "num_of_products": 1,
    "has_credit_card": 1,
    "is_active_member": 1,
    "estimated_salary": 71725.73,
    "churned": 1
  },
  {
    "customer_id": 11,
    "credit_score": 561,
    "geography": "Spain",
    "gender": "Male",
    "age": 29,
    "tenure": 7,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 0,
    "is_active_member": 1,
    "estimated_salary": 80127.46,
    "churned": 0
  },
  {
    "customer_id": 12,
    "credit_score": 720,
    "geography": "France",
    "gender": "Female",
    "age": 31,
    "tenure": 4,
    "balance": 120857.51,
    "num_of_products": 3,
    "has_credit_card": 0,
    "is_active_member": 1,
    "estimated_salary": 76390.01,
    "churned": 0
  },
  {
    "customer_id": 13,
    "credit_score": 650,
    "geography": "Germany",
    "gender": "Male",
    "age": 33,
    "tenure": 5,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 0,
    "estimated_salary": 26260.98,
    "churned": 0
  },
  {
    "customer_id": 14,
    "credit_score": 547,
    "geography": "France",
    "gender": "Female",
    "age": 35,
    "tenure": 3,
    "balance": 0.0,
    "num_of_products": 1,
    "has_credit_card": 0,
    "is_active_member": 0,
    "estimated_salary": 190857.07,
    "churned": 0
  },
  {
    "customer_id": 15,
    "credit_score": 771,
    "geography": "Germany",
    "gender": "Male",
    "age": 42,
    "tenure": 4,
    "balance": 0.0,
    "num_of_products": 1,
    "has_credit_card": 1,
    "is_active_member": 1,
    "estimated_salary": 65951.65,
    "churned": 0
  },
  {
    "customer_id": 16,
    "credit_score": 699,
    "geography": "France",
    "gender": "Female",
    "age": 36,
    "tenure": 7,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 0,
    "is_active_member": 0,
    "estimated_salary": 64327.26,
    "churned": 0
  },
  {
    "customer_id": 17,
    "credit_score": 850,
    "geography": "Spain",
    "gender": "Male",
    "age": 32,
    "tenure": 4,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 0,
    "estimated_salary": 5097.67,
    "churned": 0
  },
  {
    "customer_id": 18,
    "credit_score": 822,
    "geography": "France",
    "gender": "Female",
    "age": 34,
    "tenure": 6,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 1,
    "estimated_salary": 14406.83,
    "churned": 0
  },
  {
    "customer_id": 19,
    "credit_score": 850,
    "geography": "Spain",
    "gender": "Male",
    "age": 34,
    "tenure": 9,
    "balance": 98688.0,
    "num_of_products": 1,
    "has_credit_card": 1,
    "is_active_member": 1,
    "estimated_salary": 158684.81,
    "churned": 1
  },
  {
    "customer_id": 20,
    "credit_score": 850,
    "geography": "France",
    "gender": "Female",
    "age": 48,
    "tenure": 4,
    "balance": 0.0,
    "num_of_products": 1,
    "has_credit_card": 0,
    "is_active_member": 1,
    "estimated_salary": 128577.47,
    "churned": 0
  },
  {
    "customer_id": 21,
    "credit_score": 500,
    "geography": "France",
    "gender": "Male",
    "age": 37,
    "tenure": 3,
    "balance": 112367.34,
    "num_of_products": 1,
    "has_credit_card": 1,
    "is_active_member": 1,
    "estimated_salary": 135512.46,
    "churned": 1
  },
  {
    "customer_id": 22,
    "credit_score": 850,
    "geography": "Germany",
    "gender": "Female",
    "age": 41,
    "tenure": 5,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 0,
    "estimated_salary": 122391.71,
    "churned": 0
  },
  {
    "customer_id": 23,
    "credit_score": 699,
    "geography": "France",
    "gender": "Male",
    "age": 39,
    "tenure": 2,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 1,
    "estimated_salary": 113755.78,
    "churned": 0
  },
  {
    "customer_id": 24,
    "credit_score": 850,
    "geography": "France",
    "gender": "Female",
    "age": 40,
    "tenure": 8,
    "balance": 0.0,
    "num_of_products": 1,
    "has_credit_card": 1,
    "is_active_member": 1,
    "estimated_salary": 137181.12,
    "churned": 0
  },
  {
    "customer_id": 25,
    "credit_score": 650,
    "geography": "Spain",
    "gender": "Male",
    "age": 35,
    "tenure": 7,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 0,
    "estimated_salary": 113955.9,
    "churned": 0
  },
  {
    "customer_id": 26,
    "credit_score": 627,
    "geography": "Germany",
    "gender": "Female",
    "age": 42,
    "tenure": 7,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 1,
    "estimated_salary": 137191.12,
    "churned": 0
  },
  {
    "customer_id": 27,
    "credit_score": 666,
    "geography": "France",
    "gender": "Male",
    "age": 49,
    "tenure": 8,
    "balance": 0.0,
    "num_of_products": 1,
    "has_credit_card": 1,
    "is_active_member": 0,
    "estimated_salary": 11575.77,
    "churned": 1
  },
  {
    "customer_id": 28,
    "credit_score": 577,
    "geography": "France",
    "gender": "Female",
    "age": 31,
    "tenure": 4,
    "balance": 0.0,
    "num_of_products": 1,
    "has_credit_card": 1,
    "is_active_member": 0,
    "estimated_salary": 105772.15,
    "churned": 0
  },
  {
    "customer_id": 29,
    "credit_score": 850,
    "geography": "Spain",
    "gender": "Male",
    "age": 43,
    "tenure": 7,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 0,
    "is_active_member": 1,
    "estimated_salary": 121577.47,
    "churned": 0
  },
  {
    "customer_id": 30,
    "credit_score": 850,
    "geography": "France",
    "gender": "Female",
    "age": 40,
    "tenure": 8,
    "balance": 0.0,
    "num_of_products": 1,
    "has_credit_card": 0,
    "is_active_member": 0,
    "estimated_salary": 123683.48,
    "churned": 0
  },
  {
    "customer_id": 31,
    "credit_score": 650,
    "geography": "France",
    "gender": "Male",
    "age": 49,
    "tenure": 4,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 1,
    "estimated_salary": 85677.42,
    "churned": 0
  },
  {
    "customer_id": 32,
    "credit_score": 850,
    "geography": "France",
    "gender": "Female",
    "age": 55,
    "tenure": 7,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 0,
    "is_active_member": 0,
    "estimated_salary": 128574.85,
    "churned": 1
  },
  {
    "customer_id": 33,
    "credit_score": 700,
    "geography": "France",
    "gender": "Male",
    "age": 29,
    "tenure": 2,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 0,
    "is_active_member": 1,
    "estimated_salary": 1003.09,
    "churned": 0
  },
  {
    "customer_id": 34,
    "credit_score": 750,
    "geography": "Germany",
    "gender": "Female",
    "age": 37,
    "tenure": 2,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 1,
    "estimated_salary": 132602.88,
    "churned": 0
  },
  {
    "customer_id": 35,
    "credit_score": 850,
    "geography": "Spain",
    "gender": "Male",
    "age": 32,
    "tenure": 7,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 0,
    "is_active_member": 0,
    "estimated_salary": 111697.59,
    "churned": 0
  },
  {
    "customer_id": 36,
    "credit_score": 650,
    "geography": "Germany",
    "gender": "Female",
    "age": 36,
    "tenure": 5,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 0,
    "estimated_salary": 110714.6,
    "churned": 0
  },
  {
    "customer_id": 37,
    "credit_score": 750,
    "geography": "France",
    "gender": "Male",
    "age": 52,
    "tenure": 2,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 0,
    "estimated_salary": 129650.43,
    "churned": 1
  },
  {
    "customer_id": 38,
    "credit_score": 700,
    "geography": "France",
    "gender": "Female",
    "age": 46,
    "tenure": 3,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 0,
    "is_active_member": 1,
    "estimated_salary": 1004.5,
    "churned": 0
  },
  {
    "customer_id": 39,
    "credit_score": 850,
    "geography": "France",
    "gender": "Male",
    "age": 32,
    "tenure": 3,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 1,
    "estimated_salary": 147800.15,
    "churned": 0
  },
  {
    "customer_id": 40,
    "credit_score": 800,
    "geography": "France",
    "gender": "Female",
    "age": 41,
    "tenure": 4,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 0,
    "estimated_salary": 59748.77,
    "churned": 0
  },
  {
    "customer_id": 41,
    "credit_score": 690,
    "geography": "Germany",
    "gender": "Male",
    "age": 37,
    "tenure": 5,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 0,
    "estimated_salary": 183287.75,
    "churned": 0
  },
  {
    "customer_id": 42,
    "credit_score": 650,
    "geography": "France",
    "gender": "Female",
    "age": 40,
    "tenure": 5,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 1,
    "estimated_salary": 101347.93,
    "churned": 0
  },
  {
    "customer_id": 43,
    "credit_score": 850,
    "geography": "France",
    "gender": "Male",
    "age": 31,
    "tenure": 2,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 0,
    "is_active_member": 1,
    "estimated_salary": 110472.67,
    "churned": 0
  },
  {
    "customer_id": 44,
    "credit_score": 700,
    "geography": "Spain",
    "gender": "Female",
    "age": 34,
    "tenure": 4,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 0,
    "estimated_salary": 111732.2,
    "churned": 0
  },
  {
    "customer_id": 45,
    "credit_score": 550,
    "geography": "France",
    "gender": "Male",
    "age": 43,
    "tenure": 3,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 1,
    "estimated_salary": 120674.88,
    "churned": 0
  },
  {
    "customer_id": 46,
    "credit_score": 700,
    "geography": "France",
    "gender": "Female",
    "age": 51,
    "tenure": 7,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 0,
    "is_active_member": 0,
    "estimated_salary": 145479.8,
    "churned": 1
  },
  {
    "customer_id": 47,
    "credit_score": 850,
    "geography": "Spain",
    "gender": "Male",
    "age": 42,
    "tenure": 8,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 1,
    "estimated_salary": 101754.14,
    "churned": 0
  },
  {
    "customer_id": 48,
    "credit_score": 650,
    "geography": "France",
    "gender": "Female",
    "age": 41,
    "tenure": 4,
    "balance": 0.0,
    "num_of_products": 1,
    "has_credit_card": 1,
    "is_active_member": 0,
    "estimated_salary": 102813.88,
    "churned": 0
  },
  {
    "customer_id": 49,
    "credit_score": 700,
    "geography": "France",
    "gender": "Male",
    "age": 40,
    "tenure": 7,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 0,
    "is_active_member": 0,
    "estimated_salary": 83273.58,
    "churned": 0
  },
  {
    "customer_id": 50,
    "credit_score": 850,
    "geography": "Germany",
    "gender": "Female",
    "age": 48,
    "tenure": 3,
    "balance": 0.0,
    "num_of_products": 1,
    "has_credit_card": 1,
    "is_active_member": 1,
    "estimated_salary": 106495.47,
    "churned": 0
  },
  {
    "customer_id": 51,
    "credit_score": 690,
    "geography": "France",
    "gender": "Male",
    "age": 59,
    "tenure": 4,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 0,
    "estimated_salary": 110287.28,
    "churned": 1
  },
  {
    "customer_id": 52,
    "credit_score": 650,
    "geography": "Germany",
    "gender": "Female",
    "age": 36,
    "tenure": 1,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 0,
    "estimated_salary": 123579.16,
    "churned": 0
  },
  {
    "customer_id": 53,
    "credit_score": 550,
    "geography": "France",
    "gender": "Male",
    "age": 43,
    "tenure": 2,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 1,
    "estimated_salary": 139654.33,
    "churned": 0
  },
  {
    "customer_id": 54,
    "credit_score": 800,
    "geography": "France",
    "gender": "Female",
    "age": 28,
    "tenure": 2,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 1,
    "estimated_salary": 117951.39,
    "churned": 0
  },
  {
    "customer_id": 55,
    "credit_score": 700,
    "geography": "Germany",
    "gender": "Male",
    "age": 33,
    "tenure": 3,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 0,
    "is_active_member": 0,
    "estimated_salary": 141032.92,
    "churned": 1
  },
  {
    "customer_id": 56,
    "credit_score": 650,
    "geography": "Germany",
    "gender": "Female",
    "age": 41,
    "tenure": 1,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 0,
    "is_active_member": 1,
    "estimated_salary": 12502.41,
    "churned": 0
  },
  {
    "customer_id": 57,
    "credit_score": 650,
    "geography": "France",
    "gender": "Male",
    "age": 30,
    "tenure": 1,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 0,
    "is_active_member": 0,
    "estimated_salary": 78017.4,
    "churned": 0
  },
  {
    "customer_id": 58,
    "credit_score": 700,
    "geography": "Germany",
    "gender": "Female",
    "age": 32,
    "tenure": 2,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 1,
    "estimated_salary": 181647.04,
    "churned": 0
  },
  {
    "customer_id": 59,
    "credit_score": 650,
    "geography": "France",
    "gender": "Male",
    "age": 33,
    "tenure": 2,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 0,
    "estimated_salary": 147098.86,
    "churned": 0
  },
  {
    "customer_id": 60,
    "credit_score": 800,
    "geography": "Germany",
    "gender": "Female",
    "age": 35,
    "tenure": 2,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 1,
    "estimated_salary": 123566.75,
    "churned": 0
  },
  {
    "customer_id": 61,
    "credit_score": 600,
    "geography": "Spain",
    "gender": "Male",
    "age": 36,
    "tenure": 8,
    "balance": 0.0,
    "num_of_products": 1,
    "has_credit_card": 0,
    "is_active_member": 1,
    "estimated_salary": 124893.96,
    "churned": 0
  },
  {
    "customer_id": 62,
    "credit_score": 650,
    "geography": "France",
    "gender": "Female",
    "age": 50,
    "tenure": 2,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 1,
    "estimated_salary": 100838.12,
    "churned": 0
  },
  {
    "customer_id": 63,
    "credit_score": 650,
    "geography": "France",
    "gender": "Male",
    "age": 53,
    "tenure": 4,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 0,
    "estimated_salary": 104423.15,
    "churned": 0
  },
  {
    "customer_id": 64,
    "credit_score": 500,
    "geography": "France",
    "gender": "Female",
    "age": 40,
    "tenure": 2,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 0,
    "estimated_salary": 67936.12,
    "churned": 0
  },
  {
    "customer_id": 65,
    "credit_score": 850,
    "geography": "France",
    "gender": "Male",
    "age": 50,
    "tenure": 1,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 0,
    "is_active_member": 1,
    "estimated_salary": 99591.5,
    "churned": 0
  },
  {
    "customer_id": 66,
    "credit_score": 700,
    "geography": "France",
    "gender": "Female",
    "age": 39,
    "tenure": 2,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 0,
    "estimated_salary": 80565.84,
    "churned": 0
  },
  {
    "customer_id": 67,
    "credit_score": 650,
    "geography": "Germany",
    "gender": "Male",
    "age": 47,
    "tenure": 2,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 0,
    "is_active_member": 1,
    "estimated_salary": 1008.74,
    "churned": 0
  },
  {
    "customer_id": 68,
    "credit_score": 700,
    "geography": "Germany",
    "gender": "Female",
    "age": 51,
    "tenure": 8,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 1,
    "estimated_salary": 111812.51,
    "churned": 0
  },
  {
    "customer_id": 69,
    "credit_score": 650,
    "geography": "Spain",
    "gender": "Male",
    "age": 36,
    "tenure": 1,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 0,
    "estimated_salary": 138429.56,
    "churned": 0
  },
  {
    "customer_id": 70,
    "credit_score": 750,
    "geography": "France",
    "gender": "Female",
    "age": 28,
    "tenure": 2,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 1,
    "estimated_salary": 92947.11,
    "churned": 0
  },
  {
    "customer_id": 71,
    "credit_score": 700,
    "geography": "France",
    "gender": "Male",
    "age": 39,
    "tenure": 2,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 0,
    "is_active_member": 0,
    "estimated_salary": 135104.39,
    "churned": 0
  },
  {
    "customer_id": 72,
    "credit_score": 650,
    "geography": "Spain",
    "gender": "Female",
    "age": 35,
    "tenure": 2,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 1,
    "estimated_salary": 129542.86,
    "churned": 1
  },
  {
    "customer_id": 73,
    "credit_score": 800,
    "geography": "Germany",
    "gender": "Male",
    "age": 31,
    "tenure": 8,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 1,
    "estimated_salary": 1270.98,
    "churned": 0
  },
  {
    "customer_id": 74,
    "credit_score": 650,
    "geography": "France",
    "gender": "Female",
    "age": 37,
    "tenure": 6,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 0,
    "estimated_salary": 15505.66,
    "churned": 0
  },
  {
    "customer_id": 75,
    "credit_score": 850,
    "geography": "Spain",
    "gender": "Male",
    "age": 42,
    "tenure": 2,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 1,
    "estimated_salary": 130309.62,
    "churned": 0
  },
  {
    "customer_id": 76,
    "credit_score": 850,
    "geography": "France",
    "gender": "Female",
    "age": 41,
    "tenure": 6,
    "balance": 0.0,
    "num_of_products": 1,
    "has_credit_card": 1,
    "is_active_member": 0,
    "estimated_salary": 114730.78,
    "churned": 0
  },
  {
    "customer_id": 77,
    "credit_score": 650,
    "geography": "France",
    "gender": "Male",
    "age": 55,
    "tenure": 4,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 0,
    "estimated_salary": 128578.94,
    "churned": 1
  },
  {
    "customer_id": 78,
    "credit_score": 700,
    "geography": "France",
    "gender": "Female",
    "age": 39,
    "tenure": 7,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 1,
    "estimated_salary": 119522.45,
    "churned": 0
  },
  {
    "customer_id": 79,
    "credit_score": 650,
    "geography": "Spain",
    "gender": "Male",
    "age": 34,
    "tenure": 7,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 0,
    "is_active_member": 1,
    "estimated_salary": 129713.75,
    "churned": 0
  },
  {
    "customer_id": 80,
    "credit_score": 650,
    "geography": "France",
    "gender": "Female",
    "age": 30,
    "tenure": 4,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 0,
    "estimated_salary": 6147.45,
    "churned": 0
  },
  {
    "customer_id": 81,
    "credit_score": 700,
    "geography": "France",
    "gender": "Male",
    "age": 30,
    "tenure": 8,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 1,
    "estimated_salary": 1840.14,
    "churned": 0
  },
  {
    "customer_id": 82,
    "credit_score": 650,
    "geography": "France",
    "gender": "Female",
    "age": 30,
    "tenure": 2,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 1,
    "estimated_salary": 157374.92,
    "churned": 0
  },
  {
    "customer_id": 83,
    "credit_score": 800,
    "geography": "France",
    "gender": "Male",
    "age": 35,
    "tenure": 8,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 0,
    "estimated_salary": 132683.98,
    "churned": 0
  },
  {
    "customer_id": 84,
    "credit_score": 700,
    "geography": "France",
    "gender": "Female",
    "age": 48,
    "tenure": 8,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 1,
    "estimated_salary": 23525.38,
    "churned": 0
  },
  {
    "customer_id": 85,
    "credit_score": 850,
    "geography": "Spain",
    "gender": "Male",
    "age": 47,
    "tenure": 4,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 0,
    "estimated_salary": 118346.78,
    "churned": 0
  },
  {
    "customer_id": 86,
    "credit_score": 650,
    "geography": "Spain",
    "gender": "Female",
    "age": 37,
    "tenure": 5,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 1,
    "estimated_salary": 85907.35,
    "churned": 0
  },
  {
    "customer_id": 87,
    "credit_score": 700,
    "geography": "Germany",
    "gender": "Male",
    "age": 40,
    "tenure": 5,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 0,
    "estimated_salary": 136046.74,
    "churned": 1
  },
  {
    "customer_id": 88,
    "credit_score": 650,
    "geography": "France",
    "gender": "Female",
    "age": 36,
    "tenure": 6,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 1,
    "estimated_salary": 97752.94,
    "churned": 0
  },
  {
    "customer_id": 89,
    "credit_score": 550,
    "geography": "Germany",
    "gender": "Male",
    "age": 43,
    "tenure": 5,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 0,
    "estimated_salary": 56654.35,
    "churned": 0
  },
  {
    "customer_id": 90,
    "credit_score": 700,
    "geography": "France",
    "gender": "Female",
    "age": 55,
    "tenure": 8,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 0,
    "is_active_member": 0,
    "estimated_salary": 86006.65,
    "churned": 0
  },
  {
    "customer_id": 91,
    "credit_score": 650,
    "geography": "France",
    "gender": "Male",
    "age": 32,
    "tenure": 2,
    "balance": 0.0,
    "num_of_products": 1,
    "has_credit_card": 0,
    "is_active_member": 1,
    "estimated_salary": 65631.13,
    "churned": 0
  },
  {
    "customer_id": 92,
    "credit_score": 850,
    "geography": "Germany",
    "gender": "Female",
    "age": 53,
    "tenure": 4,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 1,
    "estimated_salary": 126972.53,
    "churned": 1
  },
  {
    "customer_id": 93,
    "credit_score": 650,
    "geography": "France",
    "gender": "Male",
    "age": 39,
    "tenure": 2,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 0,
    "estimated_salary": 144664.25,
    "churned": 0
  },
  {
    "customer_id": 94,
    "credit_score": 700,
    "geography": "France",
    "gender": "Female",
    "age": 53,
    "tenure": 8,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 0,
    "is_active_member": 1,
    "estimated_salary": 64404.34,
    "churned": 0
  },
  {
    "customer_id": 95,
    "credit_score": 650,
    "geography": "Spain",
    "gender": "Male",
    "age": 31,
    "tenure": 6,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 0,
    "estimated_salary": 127724.71,
    "churned": 0
  },
  {
    "customer_id": 96,
    "credit_score": 850,
    "geography": "France",
    "gender": "Female",
    "age": 28,
    "tenure": 2,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 1,
    "estimated_salary": 124954.32,
    "churned": 0
  },
  {
    "customer_id": 97,
    "credit_score": 650,
    "geography": "Germany",
    "gender": "Male",
    "age": 36,
    "tenure": 5,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 0,
    "estimated_salary": 104337.82,
    "churned": 0
  },
  {
    "customer_id": 98,
    "credit_score": 850,
    "geography": "France",
    "gender": "Female",
    "age": 30,
    "tenure": 2,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 1,
    "estimated_salary": 160091.06,
    "churned": 0
  },
  {
    "customer_id": 99,
    "credit_score": 700,
    "geography": "Germany",
    "gender": "Male",
    "age": 35,
    "tenure": 3,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 1,
    "is_active_member": 1,
    "estimated_salary": 11617.91,
    "churned": 0
  },
  {
    "customer_id": 100,
    "credit_score": 650,
    "geography": "France",
    "gender": "Female",
    "age": 53,
    "tenure": 3,
    "balance": 0.0,
    "num_of_products": 2,
    "has_credit_card": 0,
    "is_active_member": 0,
    "estimated_salary": 14760.52,
    "churned": 1
  }
];
